calibrate_date:
  fields:
    offset:
      required: false
      example: 1
      selector:
        number:
          min: -2
          max: 2
          mode: box
    hijri:
      required: false
      example: "1446-10-15"
      selector:
        text:
    language:
      required: false
      default: "en"
      example: "en"
      selector:
        language:
          languages:
            - "en"
            - "ar"
            - "bn"
            - "de"
            - "es"
            - "fa"
            - "fr"
            - "he"
            - "id"
            - "it"
            - "ja"
            - "ko"
            - "nl"
            - "pl"
            - "pt"
            - "pt-BR"
            - "ru"
            - "tr"
            - "uk"
            - "zh-Hans"

convert_to_hijri:
  fields:
    date:
      required: false
      example: "2025-04-14"
      selector:
        date:
    language:
      required: false
      default: "en"
      example: "en"
      selector:
        language:
          languages:
            - "en"
            - "ar"
            - "bn"
            - "de"
            - "es"
            - "fa"
            - "fr"
            - "he"
            - "id"
            - "it"
            - "ja"
            - "ko"
            - "nl"
            - "pl"
            - "pt"
            - "pt-BR"
            - "ru"
            - "tr"
            - "uk"
            - "zh-Hans"

set_day_offset:
  fields:
    offset:
      required: true
      example: 1
      selector:
        number:
          min: -2
          max: 2
          mode: box

convert_to_gregorian:
  fields:
    date:
      required: false
      example: "2025-04-14"
      selector:
        date:
    language:
      required: false
      default: "en"
      example: "en"
      selector:
        language:
          languages:
            - "en"
            - "ar"
            - "bn"
            - "de"
            - "es"
            - "fa"
            - "fr"
            - "he"
            - "id"
            - "it"
            - "ja"
            - "ko"
            - "nl"
            - "pl"
            - "pt"
            - "pt-BR"
            - "ru"
            - "tr"
            - "uk"
            - "zh-Hans"
