name: Release

on:
  release:
    types:
      - published

permissions: {}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install yq
        shell: bash
        run: |
          curl -fsSL "https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64" \
            -o /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Adjust version number
        shell: bash
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          VERSION="${VERSION#v}"
          yq -i -o json ".version=\"${VERSION}\"" \
            "${{ github.workspace }}/custom_components/hijri_calendar/manifest.json"

      - name: ZIP the integration directory
        shell: bash
        run: |
          cd "${{ github.workspace }}/custom_components/hijri_calendar"
          zip hijri_calendar.zip -r ./

      - name: Upload the ZIP file to the release
        uses: softprops/action-gh-release@7f213cdc61fa870106ccf5129596ca921cdadac18 # v2.2.1
        with:
          files: ${{ github.workspace }}/custom_components/hijri_calendar/hijri_calendar.zip
